---
log-level: debug

# Repos to search
source:
  provider: github
  organization: pantheon-systems
  repos: ['infrastructure', 'titan-mt']
  token: # Set this using the `--source.token=TOKENVALUE` command parameter

#earliest-commit: f45188308b6c4877941e83ed0214f85e54be4324
#latest-commit: f45188308b6c4877941e83ed0214f85e54be4324

# Directories (relative to cwd with command is run)
output-dir: ./output
whitelist-secret-dir: ./whitelist

# Whitelist files that match any
whitelist-path-match:
  - '_tests?\..{3,4}$'
  - '\/tests?\/'
  - '\/spec\/'

# Rules
rules:
  - name: slack-token
    processor: regex
    regex: '(xox[p|b|o|a]-[0-9]{12}-[0-9]{12}-[0-9]{12}-[a-z0-9]{32})'
  - name: facebook-oauth
    processor: regex
    regex: '[f|F][a|A][c|C][e|E][b|B][o|O][o|O][k|K].*[''|"][0-9a-f]{32}[''|"]'
  - name: twitter-oauth
    processor: regex
    regex: '[t|T][w|W][i|I][t|T][t|T][e|E][r|R].*[''|"][0-9a-zA-Z]{35,44}[''|"]'
  - name: github
    processor: regex
    regex: '[g|G][i|I][t|T][h|H][u|U][b|B].*[''|"][0-9a-zA-Z]{35,40}[''|"]'
    whitelist-code-match:
      # Check cookbook definition, git ref
      - ':ref => ''([^'']+)'''
  - name: google-oauth
    processor: regex
    regex: '("client_secret":"[a-zA-Z0-9-_]{24}")'
  - name: aws-api-key
    processor: regex
    regex: 'AKIA[0-9A-Z]{16}'
  - name: heroku-api-key
    processor: regex
    regex: '[h|H][e|E][r|R][o|O][k|K][u|U].*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}'
  - name: generic-secret
    processor: regex
    regex: '[s|S][e|E][c|C][r|R][e|E][t|T].*[''|"][0-9a-zA-Z]{32,45}[''|"]'
  - name: generic-api-key
    processor: regex
    regex: '[a|A][p|P][i|I][_]?[k|K][e|E][y|Y].*[''|"][0-9a-zA-Z]{32,45}[''|"]'
  - name: slack-webhook
    processor: regex
    regex: 'https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}'
  - name: gcp-service-account
    processor: regex
    regex: '"type": "service_account"'
  - name: twilio-api-key
    processor: regex
    regex: 'SK[a-z0-9]{32}'
  - name: password-in-url
    processor: regex
    regex: '[a-zA-Z]{3,10}://[^/\s:@]{3,20}:[^/\s:@]{3,20}@[^''"\s]+'
    whitelist-code-match:
      - '://[^/\s:@]{3,20}:\{[^/\s:@]{1,20}\}@'
      - '://[^/\s:@]{3,20}:\$db_pass@'
      - '://user:pass@'
      - '://myuser:EXTRA_S3CUR3_PASS@'
      - '://user:password@'
      - '://username:password@'
      - '://USERNAME:PASSWORD@'
      - '://bob:loblaw@'
      - '://test:secret@'
      - '://<strong>Me:Secret@'

  - name: rsa-private-key-pem
    processor: pem
    pem-type: RSA PRIVATE KEY
    whitelist-code-match:
      # This format of key is invalid
      - '-----BEGIN RSA PRIVATE KEY-----.{43}----END RSA PRIVATE KEY-----'
  - name: openssh-private-key-pem
    processor: pem
    pem-type: OPENSSH PRIVATE KEY
  - name: ec-private-key-pem
    processor: pem
    pem-type: EC PRIVATE KEY
  - name: rsa-private-key-block-pem
    processor: pem
    pem-type: PGP PRIVATE KEY BLOCK

  - name: entropy-base64
    processor: entropy
    entropy:
      charset: base64
      length-threshold: 20
      entropy-threshold: 4.5
    whitelist-code-match:
      # Skip SSH public keys
      - '\bssh-rsa AAAA[0-9A-Za-z+/]+[=]{0,3}\b'

  - name: entropy-hex
    processor: entropy
    entropy:
      charset: hex
      length-threshold: 20
      entropy-threshold: 3
    whitelist-code-match:
      # Commit hash in requirements.txt
      - '-e git\+https://[^\s\/]+/[^\s\/]+/[^\s\/]+\.git@'
