package builtin

//go:generate stringer -type ProcessorName

type ProcessorName int

const (
	URLPathParamValSetter ProcessorName = iota
	URLQueryStringParamValSetter
	PyVarAssignSetter
	PyDictFieldAssignSetter
	PyDictLiteralFieldSetter
	PyTupleSetter
	PHPVarAssignSetter
	PHPAssocArrayFieldAssignSetter
	PHPAssocArrayLiteralFieldSetter
	PHPConstDefineSetter
	JSVarAssignSetter
	JSObjFieldAssignSetter
	JSObjLiteralFieldSetter
	GoVarAssignSetter
	GoHashFieldAssignSetter
	GoHashLiteralFieldSetter
	GoFlagDefaultValSetter
	RubyVarAssignSetter
	RubyHashFieldAssignSetter
	RubyArrowParamSetter
	RubyColonParamSetter
	ConfParamSystemdServiceEnvVarSetter
	ConfParamLogstashStyleSetter
	ConfParamLogstashStyleEnvVarDefaultSetter
	ShellScriptVarAssignSetter
	ShellCmdParamValSetter
	YAMLDictFieldValSetter
	JSONObjFieldValSetter
	XMLTagValSetter
	XMLTagValKeyAsAttrSetter
	XMLAttrValSetter
	HTMLTableRowValSetter
	GenericSetter

	RSAPrivateKeyPEM
	OpenSSHPrivateKeyPEM
	ECPrivateKeyPEM
	PGPPrivateKeyBlockPEM
	DSAPrivateKeyPEM

	SlackTokenRegex
	FacebookOAuthRegex
	GoogleOAuthRegex
	TwitterRegex
	HerokuAPIKeyRegex
	SlackWebhookRegex
	GCPServiceAccountRegex
	TwilioAPIKeyRegex
	URLPasswordRegex
	GenericSecretRegex
	AWSAccessKeyIDRegex
	AWSSecretKeyRegex
	AWSMWSAuthTokenRegex
	GitHubTokenRegex
	GitHubOAuthRegex
	LinkedInClientIDRegex
	LinkedInSecretKeyRegex
	StripeAPIKeyRegex
	SquareAccessTokenRegex
	SquareOAuthSecretRegex
	PayPalBraintreeAccessTokenRegex
	SendGridAPIKeyRegex
	MailGunAPIKeyRegex
	MailChimpAPIKeyRegex
	DigitalOceanPATRegex
	DigitalOceanOAuthRegex
	DigitalOceanRefreshTokenRegex
	NuGetAPIKeyRegex

	// AI/ML Providers
	OpenAIAPIKeyRegex
	AnthropicAPIKeyRegex
	GroqAPIKeyRegex
	DeepSeekAPIKeyRegex
	XAIAPIKeyRegex
	HuggingFaceTokenRegex
	ReplicateAPITokenRegex
	ElevenLabsAPIKeyRegex

	// Cloud & Infrastructure
	GoogleCloudAPIKeyRegex
	GoogleOAuthAccessTokenRegex
	GoogleOAuthKeyRegex
	CloudflareAPITokenRegex
	CloudflareGlobalAPIKeyRegex
	AzureStorageKeyRegex
	AzureEntraSecretRegex
	SupabaseTokenRegex
	MongoDBConnectionStringRegex
	PostgreSQLConnectionStringRegex
	RedisConnectionStringRegex
	AzureDevOpsPATRegex

	// Developer Platforms & Version Control
	GitHubFineGrainedPATRegex
	GitLabTokenRegex
	NPMTokenRegex
	PyPITokenRegex
	RubyGemsTokenRegex
	ShopifyTokenRegex
	AtlassianTokenRegex
	JiraTokenRegex
	PostmanAPIKeyRegex
	FigmaPATRegex

	// Communication & Social
	DiscordBotTokenRegex
	DiscordWebhookRegex
	TelegramBotTokenRegex
	FacebookAccessTokenRegex
	FacebookSecretKeyRegex
	FacebookClientIDRegex
	TwitterSecretKeyRegex
	TwitterClientIDRegex

	// Monitoring, Observability & DevOps
	DatadogAPIKeyRegex
	DatadogAppKeyRegex
	SentryTokenRegex
	SentryOrgTokenRegex
	NewRelicAPIKeyRegex
	SplunkTokenRegex
	GrafanaCloudTokenRegex
	GrafanaServiceAccountRegex
	CircleCITokenRegex
	BuildkiteTokenRegex
	TravisCITokenRegex
	SnykKeyRegex

	// Hosting, Deployment & SaaS
	VercelTokenRegex
	NetlifyTokenRegex
	DopplerTokenRegex
	PlanetScaleTokenRegex
	PlanetScalePasswordRegex
	LaunchDarklyTokenRegex
	AlgoliaAdminKeyRegex
	OktaTokenRegex
	LinearAPIKeyRegex
	WeightsAndBiasesKeyRegex
	HashiCorpVaultTokenRegex
	MapboxTokenRegex

	// Miscellaneous content patterns
	JWTRegex
	ArtifactoryTokenRegex
	CodeClimateTokenRegex
	SonarQubeTokenRegex
	HockeyAppTokenRegex
	StackHawkAPIKeyRegex
	OutlookWebhookRegex
	WPConfigCredentialsRegex

	// Cloud & Infrastructure (Batch 1)
	AlibabaCloudKeyRegex
	DatabricksTokenRegex
	NVIDIANGCKeyRegex
	AWSSessionTokenRegex
	AzureSASTokenRegex
	AzureFunctionKeyRegex
	AzureContainerRegistryRegex
	AzureSearchAdminKeyRegex
	AzureAppConfigConnStringRegex
	AzureOpenAIKeyRegex
	AzureCosmosDBKeyRegex
	AzureBatchKeyRegex
	AzureAPIManagementKeyRegex
	ConfluentKeyRegex
	ConfluentSecretRegex
	AivenTokenRegex
	PulumiTokenRegex
	TerraformCloudTokenRegex
	InfuraAPIKeyRegex
	AlchemyAPIKeyRegex
	DigitalOceanSpacesKeyRegex
	ScalewayKeyRegex
	VultrAPIKeyRegex
	HetznerAPITokenRegex
	LinodeAPITokenRegex
	DropboxTokenRegex
	FlyIOTokenRegex
	RailwayTokenRegex
	RenderAPIKeyRegex
	CouchbaseConnStringRegex
	RabbitMQConnStringRegex
	FTPCredentialRegex
	JDBCConnStringRegex
	MySQLConnStringRegex
	ElasticsearchURLRegex
	NGrokTokenRegex
	PortainerTokenRegex
	SnowflakeKeyRegex
	CloudsmithAPIKeyRegex
	PackageCloudTokenRegex

	// DevOps & Developer Tools (Batch 2)
	BitbucketAppPasswordRegex
	DroneTokenRegex
	SourcegraphTokenRegex
	SourcegraphCodyTokenRegex
	LangSmithTokenRegex
	LangfuseSecretKeyRegex
	LangfusePublicKeyRegex
	PrefectTokenRegex
	HarnessTokenRegex
	ContentfulPATRegex
	AirtableTokenRegex
	NotionTokenRegex
	ClickUpTokenRegex
	AsanaPATRegex
	CoverallsTokenRegex
	CodemagicTokenRegex
	CodacyTokenRegex
	ScrutinizerTokenRegex
	PercyTokenRegex
	PagerDutyAPIKeyRegex
	OpsgenieAPIKeyRegex
	HoneycombTokenRegex
	BetterStackTokenRegex
	LogglyTokenRegex
	LogzIOTokenRegex
	PostHogTokenRegex
	SegmentAPIKeyRegex
	MixpanelTokenRegex
	AmplitudeAPIKeyRegex
	EndorLabsTokenRegex
	NightfallAPIKeyRegex
	SentryDSNRegex
	JupiterOneTokenRegex
	WizTokenRegex
	DetectifyKeyRegex
	MicrosoftTeamsWebhookRegex
	ZapierWebhookRegex
	TinesWebhookRegex
	GitLabRunnerTokenRegex
	DockerHubTokenRegex

	// Marketing, Analytics & CRM (Batch 5)
	MailerLiteTokenRegex
	ConvertKitTokenRegex
	OmnisendKeyRegex
	CustomerIOKeyRegex
	KlaviyoPrivateKeyRegex
	IterableAPIKeyRegex
	BrevoAPIKeyRegex
	ActiveCampaignKeyRegex
	DripAPIKeyRegex
	GetResponseKeyRegex
	MoosendKeyRegex
	SendinBlueKeyRegex
	EventbriteKeyRegex
	TypeformTokenRegex
	SurveyMonkeyTokenRegex
	FullStoryTokenRegex
	HotjarTokenRegex
	OptimizelyTokenRegex
	AppsflyerKeyRegex
	BranchIOKeyRegex
	ChargebeeKeyRegex
	RecurlyAPIKeyRegex
	PaddleKeyRegex
	ChargifyKeyRegex
	ZuoraKeyRegex
	BigCommerceTokenRegex
	WooCommerceKeyRegex
	ContentstackTokenRegex
	StoryblokTokenRegex
	GraphCMSTokenRegex
	PrismicTokenRegex
	StrapiAPIKeyRegex
	GhostAdminKeyRegex
	ButterCMSKeyRegex
	DatoCMSTokenRegex
	HarperDBKeyRegex
	FaunaDBKeyRegex
	PlanetScaleOAuthRegex
	TursoTokenRegex
	NeonTokenRegex

	// SaaS & Communication (Batch 3)
	TwilioAccountSIDRegex
	TelnyxAPIKeyRegex
	VonageAPIKeyRegex
	PlivoAuthTokenRegex
	MessageBirdKeyRegex
	SendBirdKeyRegex
	MandrillAPIKeyRegex
	SparkPostTokenRegex
	CourierAPIKeyRegex
	PostmarkTokenRegex
	IntercomTokenRegex
	FreshdeskTokenRegex
	FreshbooksTokenRegex
	HubSpotAPIKeyRegex
	SalesforceTokenRegex
	DocuSignKeyRegex
	FastlyTokenRegex
	MattermostTokenRegex
	WebflowTokenRegex
	DeepgramAPIKeyRegex
	AssemblyAIKeyRegex
	CohereAPIKeyRegex
	MistralAPIKeyRegex
	FireworksAPIKeyRegex
	TogetherAPIKeyRegex
	PerplexityAPIKeyRegex
	SlackAppTokenRegex
	TrelloAPIKeyRegex
	MondayTokenRegex
	TodoistTokenRegex
	LarkSuiteTokenRegex
	SmartsheetTokenRegex
	Auth0ClientSecretRegex
	OneLoginSecretRegex
	JumpCloudAPIKeyRegex
	PipedreamAPIKeyRegex
	WebexBotTokenRegex
	TwitchAccessTokenRegex
	SignalWireTokenRegex
	TextMagicKeyRegex


	// Data Platforms & Misc (Batch 6)
	SplunkObservabilityTokenRegex
	SumoLogicKeyRegex
	ElasticCloudKeyRegex
	TimescaleDBTokenRegex
	ClickHouseTokenRegex
	InfluxDBTokenRegex
	CockroachDBTokenRegex
	RedisCloudTokenRegex
	UpstashTokenRegex
	OpenSearchKeyRegex
	PagerDutyServiceKeyRegex
	StatusPageKeyRegex
	UptimeRobotKeyRegex
	DatadogRUMTokenRegex
	GoogleMapsAPIKeyRegex
	MapTilerKeyRegex
	TomTomAPIKeyRegex
	HereAPIKeyRegex
	TwelveDatAPIKeyRegex
	AlphaVantageKeyRegex
	PolygonIOKeyRegex
	FinnhubTokenRegex
	CoinGeckoKeyRegex
	BlockchainInfoKeyRegex
	AWSCognitoTokenRegex
	FirebaseAPIKeyRegex
	FirebaseCloudMsgRegex
	AppCenterTokenRegex
	ExpoTokenRegex
	TestFlightTokenRegex
	SonarCloudTokenRegex
	CoverityTokenRegex
	FossaKeyRegex
	WhitesourceKeyRegex
	BlackDuckTokenRegex
	NetlifyDeployKeyRegex
	CloudinaryURLRegex
	ImgixTokenRegex
	FastlyAPITokenRegex
	AkamaiTokenRegex


	// Payments, Blockchain & Security (Batch 4)
	FlutterwaveKeyRegex
	PaystackKeyRegex
	RazorpayKeyRegex
	EtherscanKeyRegex
	BSCScanKeyRegex
	PinataAPIKeyRegex
	MoralisAPIKeyRegex
	CoinbaseKeyRegex
	PlaidAccessTokenRegex
	PlaidSecretKeyRegex
	WiseAPIKeyRegex
	DwollaKeyRegex
	LemonSqueezyKeyRegex
	SauceLabsTokenRegex
	BrowserStackKeyRegex
	BitlyTokenRegex
	SnipcartAPIKeyRegex
	GumroadAccessTokenRegex
	RapidAPIKeyRegex
	IPInfoTokenRegex
	ShodanKeyRegex
	VirusTotalAPIKeyRegex
	SecurityTrailsKeyRegex
	URLScanKeyRegex
	CensysKeyRegex
	SanityTokenRegex
	WistiaTokenRegex
	StripePaymentIntentRegex
	SquareAppTokenRegex
	OneSignalKeyRegex
	SSHPassRegex
	GrafanaAPIKeyRegex
	FrameIOTokenRegex
	StytchSecretRegex
	KlaviyoKeyRegex
	LaravelAppKeyRegex
	GenericAPIKeyRegex
	RobinhoodCryptoKeyRegex
	ZohoTokenRegex
	GoDaddyAPIKeyRegex

	// File Signature processors
	PEMFileExtensionFileSig
	PKCS12FileExtensionFileSig
	P12FileExtensionFileSig
	PFXFileExtensionFileSig
	ASCFileExtensionFileSig
	OVPNFileExtensionFileSig
	CSCFGFileExtensionFileSig
	RDPFileExtensionFileSig
	MDFFileExtensionFileSig
	SDFFileExtensionFileSig
	SQLiteFileExtensionFileSig
	SQLite3FileExtensionFileSig
	BEKFileExtensionFileSig
	TPMFileExtensionFileSig
	FVEFileExtensionFileSig
	JKSFileExtensionFileSig
	PSafe3FileExtensionFileSig
	AgileKeychainFileExtensionFileSig
	KeychainFileExtensionFileSig
	PCAPFileExtensionFileSig
	GnuCashFileExtensionFileSig
	KWalletFileExtensionFileSig
	TBLKFileExtensionFileSig
	DayOneFileExtensionFileSig
	PPKFileExtensionFileSig
	SQLDumpFileExtensionFileSig
	NetrcFileExtensionFileSig
	LogFileExtensionFileSig

	OTRPrivateKeyFileSig
	SecretTokenRBFileSig
	CarrierWaveRBFileSig
	DatabaseYMLFileSig
	OmniauthRBFileSig
	SettingsPYFileSig
	CredentialsXMLFileSig
	LocalSettingsPHPFileSig
	FavoritesPlistFileSig
	KnifeRBFileSig
	ProftpdPasswdFileSig
	RobomongoJSONFileSig
	FileZillaXMLFileSig
	RecentServersXMLFileSig
	TerraformTFVarsFileSig
	DotExportsFileSig
	DotFunctionsFileSig
	DotExtraFileSig
	HerokuJSONFileSig
	DumpSQLFileSig
	MongoidYMLFileSig
	SalesforceJSFileSig
	ShellRCFileSig
	ShellProfileFileSig
	ShellAliasesFileSig
	GemrcFileSig
	DockerCfgFileSig
	NpmrcFileSig
	EnvFileSig
	HtpasswdFileSig
	KeystoreFileSig

	SSHRSAKeyFileSig
	SSHDSAKeyFileSig
	SSHEd25519KeyFileSig
	SSHECDSAKeyFileSig
	SSHConfigFileSig
	AWSCredentialsFileSig
	DockerConfigJSONFileSig
	BashHistoryFileSig
	ZshHistoryFileSig
	MySQLHistoryFileSig
	PsqlHistoryFileSig
	IRBHistoryFileSig
	ConsoleHistoryFileSig
	SSHKnownHostsFileSig
	IdeaWebServersXMLFileSig
	VSCodeSFTPJSONFileSig
	EtcShadowFileSig
	EtcPasswdFileSig
	FirefoxLoginsJSONFileSig
	SShellHistoryFileSig
	LessHistoryFileSig
	GitCredentialsFileSig
	GnuPGFileSig
	S3CFGFileSig
	WgetHSTSFileSig
	PerlHistoryFileSig
	FTPHistoryFileSig
	TerraformTFStateFileSig
	AWSConfigFileSig
	GCloudConfigFileSig
	KubeConfigFileSig
	PGPassFileSig
	IntellIJDatasourcesFileSig
	AppSettingsJSONFileSig
	WebConfigFileSig
	DBConfigPHPFileSig
	WpConfigPHPFileSig
	ConfigIncPHPFileSig
	KeystorePropertiesFileSig
	KeyPairFileSig

	Base64Entropy
	HexEntropy
)
